### ISSUE TITLE
mlp问题请教

### ISSUE THREAD

**Issue by sunbeansoft** [DSXiangLi/CTR#4]
拜读了https://www.cnblogs.com/gogoSandy/p/12658051.html 和emmlp的实现，请教一个问题
EmbeddingInput 中 对于sparse feature为什么要单独做 tf.matmul(sparse_input, weight) op？

**Comment by DSXiangLi** [comment]
@sunbeansoft 那里其实写的有些复杂，可能是我刚开始想把dimension整明白就没用feature_column的API，忘记自己当时咋想的了。。。不过其实就是做了embeddinng_lookup， 把所有onehot的离散变量映射到了embedding_dim的连续变量，然后再拼接成了一个大的dense input，和tf.feature_column.embedding_column做了相似的事情。

**Comment by sunbeansoft** [comment]
明白了，多谢分享。ctr项目很赞
