### ISSUE TITLE
PNN模型中代码疑问

### ISSUE THREAD

**Issue by TangDouOVO** [DSXiangLi/CTR#5]
你好，看了PNN下PNN.py中关于OPNN下的代码。有两个疑问：
1.outer_product = tf.concat(outer_collection, axis=1)这句加不加有什么用吗？还是其他什么原因？
2.“tf.einsum('ai,aj->aij',vi,vj)”这一句怎么理解呢？和论文中哪一部分对应呢？

**Comment by DSXiangLi** [comment]
这里对应的是原始的OPNN的计算
einsum是对特征向量i和j做外积计算：einsum('i,j->ij', u, v)  # output[i,j] = u[i]*v[j]，这样每个向量对会得到batch * emb * emb的外积矩阵，reshape之后得到batch *(emb*emb)特征向量
concat：是对以上所有特征两两外积得到的矩阵进行拼接得到fc层之间的dense输入 batch * (feature_pair * emb * emb） 

这一步space和time复杂度很高，论文中用了superposition也就是sum-pooling来降维不过我代码里是原始的OPNN计算

**Comment by TangDouOVO** [comment]
你好，感谢回复！
1.论文中提到要用W和P做tensor inner product。所以OPNN这里是怎么体现的呢？我一开始以为这里的einsum是做内积，回复中说做外积，所以我不太清楚这样做能体现W和P做tensor inner product吗。代码里的w和p是在定义的embedding_matrix里吗？
2.tf.concat(outer_collection, axis=1)我有点理解了，但是PNN.py代码中的concat只有outer_collection这一个做拼接，这样不是相当于没有拼接吗，按理说不应该是两个吗，即
outer_product  = []
outer_product = tf.concat([outer_product ,outer_collection ], axis=1)

**Comment by DSXiangLi** [comment]
1. C. Outer Product-based Neural Network: 在论文的这里
2. IPNN不用拼接内积得到的直接是所有特征的交互结果，(batch*feature*emb) * (batch *emb * feature) -> batch * feature * feature
3. 拼接内积和外积交互结果是在tf.variable_scope('fc1')那里

**Comment by TangDouOVO** [comment]
非常感谢！我再研究研究。
