### ISSUE TITLE
NFM模型代码疑问

### ISSUE THREAD

**Issue by TangDouOVO** [DSXiangLi/CTR#6]
你好，请问NFM代码中model_fn_sparse函数是做什么的呢？model_fn_dense这个函数不是已经实现论文中的模型了吗？多出的这个model_fn_sparse是做什么的呢？

**Comment by DSXiangLi** [comment]
一个是针对sparse输入，一个是针对dense输入，要看的你的输入格式是什么

**Comment by TangDouOVO** [comment]
这里说的sparse是指在特征工程阶段将所有特征one-hot编码吗？dense是对sparse特征进行embedding处理吗？

**Comment by DSXiangLi** [comment]
指的是categorical特征的数据格式，dense去看census数据集，sparse去看frappe

**Comment by TangDouOVO** [comment]
谢谢！
